{application,saloon,
             [{description,"Saloon for cowboys"},
              {vsn,"0.1.0"},
              {registered,[]},
              {applications,[kernel,inets,stdlib,crypto,public_key,ssl,
                             fission,cowboy]},
              {mod,{saloon_app,[]}},
              {env,[]},
              {modules,[saloon_app,saloon_auth,saloon_ctx,saloon_init,
                        saloon_sup,saloon_util]}]}.
